"""add blob

Revision ID: 1794534ffff0
Revises: 5c893e577498
Create Date: 2024-09-19 00:48:01.421383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1794534ffff0'
down_revision = '5c893e577498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blob', mysql.MEDIUMBLOB(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recogs', schema=None) as batch_op:
        batch_op.drop_column('blob')

    # ### end Alembic commands ###
