"""add name

Revision ID: 4422d5ab40d4
Revises: 14594126fb18
Create Date: 2024-09-09 01:00:11.915412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4422d5ab40d4'
down_revision = '14594126fb18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recogs', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
